#include "ArmadilloPrecomputedInterpolationTable.hpp"
#include "config.hpp" // FUNC_USE_BOOST_AUTODIFF, FUNC_USE_ARMADILLO

#ifndef FUNC_USE_ARMADILLO
#error "ArmadilloRegistrarDefinitions needs Armadillo"
#endif

FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(UniformArmadilloPrecomputedInterpolationTable,4);
FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(UniformArmadilloPrecomputedInterpolationTable,5);
FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(UniformArmadilloPrecomputedInterpolationTable,6);
FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(UniformArmadilloPrecomputedInterpolationTable,7);

#ifdef FUNC_USE_BOOST_AUTODIFF
FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(NonUniformArmadilloPrecomputedInterpolationTable,4);
FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(NonUniformArmadilloPrecomputedInterpolationTable,5);
FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(NonUniformArmadilloPrecomputedInterpolationTable,6);
FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(NonUniformArmadilloPrecomputedInterpolationTable,7);
FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(NonUniformPseudoArmadilloPrecomputedInterpolationTable,4);
FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(NonUniformPseudoArmadilloPrecomputedInterpolationTable,5);
FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(NonUniformPseudoArmadilloPrecomputedInterpolationTable,6);
FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(NonUniformPseudoArmadilloPrecomputedInterpolationTable,7);

#include "PadeTable.hpp"

FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(UniformPadeTable,1,1);
FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(UniformPadeTable,2,1);
FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(UniformPadeTable,3,1);
FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(UniformPadeTable,4,1);
FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(UniformPadeTable,5,1);
FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(UniformPadeTable,6,1);

FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(UniformPadeTable,2,2);
FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(UniformPadeTable,3,2);
FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(UniformPadeTable,4,2);
FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(UniformPadeTable,5,2);

FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(UniformPadeTable,3,3);
FUNC_REGISTER_EACH_TEMPLATED_ULUT_IMPL(UniformPadeTable,4,3);

// TODO Add nonuniform versions of the Pade tables

#endif
